### ISSUE TITLE
Crash in 1.18.5

### ISSUE THREAD

**Issue by batekulve** [stinky-lizard/EasyLightLevels#1]
Toggling .lightlvl on crashes the game in version 1.18.5. Here is the crash log in my case:

> Game Version: v1.18.5 (Stable)
6/6/2023 9:36:34 PM: Critical error occurred
Loaded Mods: acorns@0.5.1, aculinaryartillery@1.0.12, backpackpackplus@1.0.3, betterruins@0.1.1, hqzlights@1.1.1, fulldrop@1.0.0, HangingOilLamps@1.0.1, hungrywakeup@1.0.1, leaflanternlining@1.1.1, reducedarmornegatives@1.0.4, meteoricexpansion@1.2.4, moredrifterloot@1.5.4, nooffhandhunger@1.0.0, primitivesurvival@3.2.1, rackablefirestarter@1.0.0, ropebucket@1.0.0, speararrowheadbits@1.1.0, sticksfromfirewood@1.0.0, superfuel@2.0.7, translocatorengineeringredux@1.4.2, game@1.18.5, wildcraft@1.6.6, animalcages@2.1.5, egocaribautomapmarkers@2.5.0, betterfirepit@1.1.0, bonfires@0.2.1, carryon@1.1.0, commonlib@2.1.1, crateful@1.0.3, darkerdrifterspawns@1.0.1, easylightlevels@1.0.2, expandedfoods@1.6.6, farmlanddropssoil@1.4.0, fixhandbookclutter@1.0.5, hudclock@3.2.0, neutanm@1.0.0, prospectorinfo@4.3.0, resmeltableslight@1.0.0, stonebakeoven@1.0.3, STS@1.0.3, th3dungeon@0.1.2, creative@1.18.5, survival@1.18.5, wildfarmingrevival@1.0.5, workbenchexpansion@1.6.3, metalrecovery@0.1.19-pre.1, accessibilitytweaks@3.3.2, knapster@2.4.2, cavebeacons@1.0.7, morecandles@1.1.0, ropetongs@1.2.0, stonequarry@3.0.1, xinvtweaks@1.5.3
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at easylightlevels.ELLCoreSystem.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by batekulve** [comment]
The issue is probably in line 148 of Core.cs. Try changing the reference to `player.EntityPos.AsBlockPos` as referenced [here.](https://apidocs.vintagestory.at/api/Vintagestory.API.Common.Entities.EntityPos.html)

**Comment by stinky-lizard** [comment]
This seems to have been fixed by a recompile. The offending field has been unchanged, so perhaps it was a problem with differing .NET versions (recompile updated it 4.6.1 to 4.8).
